# layout -- 布局相关
# language: zh-CN

## menu 导航菜单显示
menu:
- page: 首页
  url: /
  icon: fa-home
- page: 开源
  url: /open
  icon: fa-github
- page: 招聘
  url: /recruit
  icon: fa-handshake-o
- page: 公众号
  url: /vipcn
  icon: fa-pagelines
- page: 关于我
  url: /about
  icon: fa-user-circle-o

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## 通用时间格式化
date_format: YYYY-MM-DD HH:mm:ss

# 各个小工具的设置

## widgets
widgets:
- author
- social
- category
- archive
- tagcloud
- friends

## 作者信息
author:
    name: 王振超，「花名：予尊」
    position: 关注服务端技术、大数据方向
    slogan: 声明：本站所引用资源若存在侵权，请<a href="mailto://zhenchao.wang@hotmail">邮件</a>告知！

## 通知栏公告设置
notice:

## 社交设置
social:
 - name: Github
   icon: github
   href: //github.com/plotor
 - name: Email
   icon: envelope-o
   href: mailto:zhenchao.wang@hotmail.com
 - name: Tencent QQ
   icon: qq
   href: /
 - name: Sina Microblog
   icon: weibo
   href: /
 - name: QQ Group
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   show_count: true
   order: -1

## 彩色标签云设置
tagcloud_config:
   min_font: 1
   max_font: 1
   unit: em
   amount: 100
   color: true
   orderby: 'count'

## 友链设置
links:
  - 武汉大学NLP研究中心: http://nlp.whu.edu.cn

# 主题自定义个性化配置

## 网站宣传语
branding:

## 首页文章简介的图片占位符
placeholder: ./img/loading.gif

## 缩略图自定义随机图片
defaultImgs:
  - /img/default.png

## 截取文章首页描述字数
excerptLength: 120

## 当无目录时的显示文字，默认为'无'
noCategoryText: '无'

## 代码高亮配置：[default,github,foundation,googlecode,monokai-sublime,monokai,xcode,vs2015,tomorrow,hybrid]
highlightTheme: monokai-sublime

## ICON配置
fontAwesome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css

## 文章过期提醒功能
warning:
  days: 1024
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 添加版权保护
archiveCopyright:
  enable: true
  tip: '版权所有，商业转载请联系作者，非商业转载请注明出处'

## 版权声明文字，支持html/text，但不要使用<li>标签
cc: |-
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">
      本博客所有文章除特别声明外，均采用 CC BY-NC-SA 4.0 许可协议
      </a>

## 过低版本的浏览器提醒文字
outdated_browser_text: '你使用的浏览器版本过低，为了你更好的阅读体验，请更新浏览器的版本或者使用其他现代浏览器，比如Chrome、Firefox、Safari等。'

## 主题评论
### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论
uyan:
  enable: false
  uyan_id: 2081622

### 畅言评论
changyan:
  enable: true
  appid: cysVsEtac
  appkey: 966bea4f406651be0a6c237e63a2cd51

# AddThis
addthis:
  enable: true
  pubid: ra-5a08317dc70419ca

## 网站访问统计

### 网盟CNZZ统计
cnzz_anaylytics: 1258616757

### 百度统计
baidu_anaylytics:

### 谷歌统计
google_anaylytics:

### 百度文章推送
baidu_push:

# 网站主题配置
since: 2018
robot: 'all'  ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.1.0
